services:
  - type: worker
    name: shuzbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DISCORD_TOKEN
        sync: false